const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  send: (channel, data) => ipcRenderer.send(channel, data),
  on: (channel, func) => ipcRenderer.on(channel, (_event, ...args) => func(...args)),
  getStore: (key) => ipcRenderer.invoke('settings:get', key),
  checkDirectoryHasFiles: (dirPath) => ipcRenderer.invoke('myzap:checkDirectoryHasFiles', dirPath),
  cloneRepository: (dirPath, envContent, reinstall = false) => ipcRenderer.invoke('myzap:cloneRepository', dirPath, envContent, reinstall),
  iniciarMyZap: (dirPath) => ipcRenderer.invoke('myzap:iniciarMyZap', dirPath),
  prepareMyZapAutoConfig: (forceRemote = false) => ipcRenderer.invoke('myzap:prepareAutoConfig', forceRemote),
  getAutoConfigDebug: () => ipcRenderer.invoke('myzap:getAutoConfigDebug'),
  getPrivilegeStatus: () => ipcRenderer.invoke('myzap:getPrivilegeStatus'),
  ensureMyZapStarted: (forceRemote = false) => ipcRenderer.invoke('myzap:ensureStarted', forceRemote),
  getConnectionStatus: () => ipcRenderer.invoke('myzap:getConnectionStatus'),
  getSessionSnapshot: () => ipcRenderer.invoke('myzap:getSessionSnapshot'),
  verifyRealStatus: () => ipcRenderer.invoke('myzap:verifyRealStatus'),
  startSession: () => ipcRenderer.invoke('myzap:startSession'),
  deleteSession: () => ipcRenderer.invoke('myzap:deleteSession'),
  sendTestMessage: () => ipcRenderer.invoke('myzap:sendTestMessage'),
  updateIaConfig: (mensagemPadrao) => ipcRenderer.invoke('myzap:updateIaConfig', mensagemPadrao),
  getCapabilitySnapshot: () => ipcRenderer.invoke('myzap:getCapabilitySnapshot'),
  saveCapabilityPreferences: (preferences) => ipcRenderer.invoke('myzap:saveCapabilityPreferences', preferences),
  getLocalServiceStatus: () => ipcRenderer.invoke('myzap:getLocalServiceStatus'),
  saveLocalStartPreferences: (preferences) => ipcRenderer.invoke('myzap:saveLocalStartPreferences', preferences),
  startExternalMyZapNow: () => ipcRenderer.invoke('myzap:startExternalNow'),
  installExternalMyZapAutoStart: () => ipcRenderer.invoke('myzap:installExternalAutoStart'),
  removeExternalMyZapAutoStart: () => ipcRenderer.invoke('myzap:removeExternalAutoStart'),
  getExternalMyZapAutoStartState: () => ipcRenderer.invoke('myzap:getExternalAutoStartState'),
  startQueueWatcher: () => ipcRenderer.invoke('myzap:startQueueWatcher'),
  stopQueueWatcher: () => ipcRenderer.invoke('myzap:stopQueueWatcher'),
  getQueueWatcherStatus: () => ipcRenderer.invoke('myzap:getQueueWatcherStatus'),
  getQueuePendentes: () => ipcRenderer.invoke('myzap:getQueuePendentes'),
  getQueueRecentMessages: () => ipcRenderer.invoke('myzap:getQueueRecentMessages'),
  forceQueueCycle: () => ipcRenderer.invoke('myzap:forceQueueCycle'),
  getQueueLogs: (maxLines) => ipcRenderer.invoke('myzap:getQueueLogs', maxLines),
  saveEnvSecrets: (secrets) => ipcRenderer.invoke('myzap:saveEnvSecrets', secrets),
  readEnvSecrets: () => ipcRenderer.invoke('myzap:readEnvSecrets'),
  resetEnvironment: (options) => ipcRenderer.invoke('myzap:resetEnvironment', options),
  getStateSnapshot: () => ipcRenderer.invoke('myzap:getStateSnapshot'),
  clearUserRemovedFlag: () => ipcRenderer.invoke('myzap:clearUserRemovedFlag'),
  getManualSetupInfo: () => ipcRenderer.invoke('myzap:getManualSetupInfo'),
  openManualSetupGuide: () => ipcRenderer.invoke('myzap:openManualSetupGuide'),
  openManualSetupTargetDirectory: () => ipcRenderer.invoke('myzap:openManualSetupTargetDirectory'),
  openManualSetupLink: (kind) => ipcRenderer.invoke('myzap:openManualSetupLink', kind),
});
